### ISSUE TITLE
Ambiguedad de respuestas

### ISSUE THREAD

**Issue by EncryptEx** [Disashop/hackudc24#2]
![image](https://github.com/Disashop/hackudc24/assets/41539618/0aefd5a2-2efa-48a6-8e95-5b964160642f)
Buenas, me digiro a ustedes para preguntarles sobre este tema: 
- se trata de un campo de tipo select, con valor default "false" pero las opciones son "sí" y "no". Ahora parece facil hacer el parse, pero imaginad que es rojo y azul, cuál es el "falso"?. El contrato de api debería cumplir con:
- El default value debe estar dentro de las opciones?
Quedo a su disposicion y/o mañana nos pasamos por el stand

**Comment by angelpinheiro** [comment]
Hola @EncryptEx, se trata de una errata. El default value, si existe, debería estar dentro de las posibles opciones de respuesta. Simplemente cambiad ese valor en la respuesta de vuestro mock. El nuestro ya está actualizado!

**Comment by bara666** [comment]
Si estoy de acuerdo, él valor del campo se define como de un tipo variable y es uno de los valores del campo select. Pero en este caso de prueba se ha puesto un false indicando que no hay un valor por defecto, y esta sin documentar.
